#############################################################################
# Makefile for building: EVM_CPP
# Generated by qmake (3.0) (Qt 5.1.0) on: ?? 8? 2 23:21:35 2014
# Project:  EVM_CPP.pro
# Template: app
# Command: /opt/Qt5.1.0/5.1.0/gcc_64/bin/qmake -o Makefile EVM_CPP.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++ -I. -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 -I/opt/Qt5.1.0/5.1.0/gcc_64/include -I/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets -I/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui -I/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Qt5.1.0/5.1.0/gcc_64 -Wl,-rpath,/opt/Qt5.1.0/5.1.0/gcc_64/lib
LIBS          = $(SUBLIBS) `pkg-config --libs opencv` -ldl -L/opt/Qt5.1.0//5.1.0/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/Qt5.1.0/5.1.0/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		videothread.cpp \
		process.cpp \
		magnify.cpp \
		paramcontroler.cpp moc_mainwindow.cpp \
		moc_videothread.cpp \
		moc_paramcontroler.cpp
OBJECTS       = main.o \
		mainwindow.o \
		videothread.o \
		process.o \
		magnify.o \
		paramcontroler.o \
		moc_mainwindow.o \
		moc_videothread.o \
		moc_paramcontroler.o
DIST          = /opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/lex.prf \
		EVM_CPP.pro \
		EVM_CPP.pro
QMAKE_TARGET  = EVM_CPP
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = EVM_CPP


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_paramcontroler.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EVM_CPP.pro /opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/lex.prf \
		EVM_CPP.pro \
		/opt/Qt5.1.0/5.1.0/gcc_64/lib/libQt5Widgets.prl \
		/opt/Qt5.1.0/5.1.0/gcc_64/lib/libQt5Gui.prl \
		/opt/Qt5.1.0/5.1.0/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile EVM_CPP.pro
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resources.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/moc.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/uic.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/lex.prf:
EVM_CPP.pro:
/opt/Qt5.1.0/5.1.0/gcc_64/lib/libQt5Widgets.prl:
/opt/Qt5.1.0/5.1.0/gcc_64/lib/libQt5Gui.prl:
/opt/Qt5.1.0/5.1.0/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile EVM_CPP.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/EVM_CPP1.0.0 || mkdir -p .tmp/EVM_CPP1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/EVM_CPP1.0.0/ && $(COPY_FILE) --parents mainwindow.h videothread.h process.h magnify.h error.h paramcontroler.h .tmp/EVM_CPP1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp videothread.cpp process.cpp magnify.cpp paramcontroler.cpp .tmp/EVM_CPP1.0.0/ && $(COPY_FILE) --parents mainwindow.ui paramcontroler.ui .tmp/EVM_CPP1.0.0/ && (cd `dirname .tmp/EVM_CPP1.0.0` && $(TAR) EVM_CPP1.0.0.tar EVM_CPP1.0.0 && $(COMPRESS) EVM_CPP1.0.0.tar) && $(MOVE) `dirname .tmp/EVM_CPP1.0.0`/EVM_CPP1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/EVM_CPP1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_qtwayland-client-header_make_all:
compiler_qtwayland-client-header_clean:
compiler_qtwayland-server-header_make_all:
compiler_qtwayland-server-header_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_videothread.cpp moc_paramcontroler.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_videothread.cpp moc_paramcontroler.cpp
moc_mainwindow.cpp: /opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_power.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qicon.h \
		videothread.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QThread \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qthread.h \
		process.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		magnify.h \
		paramcontroler.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QWidget \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QString \
		error.h \
		mainwindow.h
	/opt/Qt5.1.0//5.1.0/gcc_64/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_videothread.cpp: /opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QThread \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qthread.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_power.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject_impl.h \
		process.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		magnify.h \
		videothread.h
	/opt/Qt5.1.0//5.1.0/gcc_64/bin/moc $(DEFINES) $(INCPATH) videothread.h -o moc_videothread.cpp

moc_paramcontroler.cpp: /opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QWidget \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_power.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QString \
		process.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		magnify.h \
		error.h \
		paramcontroler.h
	/opt/Qt5.1.0//5.1.0/gcc_64/bin/moc $(DEFINES) $(INCPATH) paramcontroler.h -o moc_paramcontroler.cpp

compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_qtwayland-client-code_make_all:
compiler_qtwayland-client-code_clean:
compiler_qtwayland-server-code_make_all:
compiler_qtwayland-server-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_paramcontroler.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_paramcontroler.h
ui_mainwindow.h: mainwindow.ui
	/opt/Qt5.1.0/5.1.0/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_paramcontroler.h: paramcontroler.ui
	/opt/Qt5.1.0/5.1.0/gcc_64/bin/uic paramcontroler.ui -o ui_paramcontroler.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_power.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qicon.h \
		videothread.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QThread \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qthread.h \
		process.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		magnify.h \
		paramcontroler.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QWidget \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QString \
		error.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_power.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qicon.h \
		videothread.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QThread \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qthread.h \
		process.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		magnify.h \
		paramcontroler.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QWidget \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QString \
		error.h \
		ui_mainwindow.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QVariant \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QAction \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qaction.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qactiongroup.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qinputmethod.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QButtonGroup \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qbuttongroup.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QHeaderView \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qheaderview.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractitemview.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qabstractitemmodel.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qitemselectionmodel.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qstyleoption.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qvalidator.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qregularexpression.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qslider.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractslider.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qstyle.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtabbar.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qrubberband.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QMenuBar \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qmenubar.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qmenu.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QPushButton \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qpushbutton.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractbutton.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QStatusBar \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qstatusbar.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QToolBar \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtoolbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

videothread.o: videothread.cpp videothread.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QThread \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qthread.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_power.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject_impl.h \
		process.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		magnify.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videothread.o videothread.cpp

process.o: process.cpp process.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		magnify.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o process.o process.cpp

magnify.o: magnify.cpp magnify.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o magnify.o magnify.cpp

paramcontroler.o: paramcontroler.cpp paramcontroler.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QWidget \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_power.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QString \
		process.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/flann/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		/usr/local/include/opencv2/flann/random.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/legacy/compat.hpp \
		/usr/local/include/opencv2/core/internal.hpp \
		/usr/local/include/opencv2/core/eigen.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		magnify.h \
		error.h \
		ui_paramcontroler.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/QVariant \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QAction \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qaction.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qicon.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qactiongroup.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qinputmethod.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QButtonGroup \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qbuttongroup.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QGroupBox \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qgroupbox.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QHeaderView \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qheaderview.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractitemview.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qabstractitemmodel.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qitemselectionmodel.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qstyleoption.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qvalidator.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtCore/qregularexpression.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qslider.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractslider.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qstyle.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtabbar.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qrubberband.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QLineEdit \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qlineedit.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtextcursor.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtextformat.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QPushButton \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qpushbutton.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qabstractbutton.h \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/QRadioButton \
		/opt/Qt5.1.0/5.1.0/gcc_64/include/QtWidgets/qradiobutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paramcontroler.o paramcontroler.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_videothread.o: moc_videothread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_videothread.o moc_videothread.cpp

moc_paramcontroler.o: moc_paramcontroler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_paramcontroler.o moc_paramcontroler.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

